#!/bin/sh

## mount
mount -n -t proc     proc     /proc
mount -n -t sysfs    sysfs    /sys
mount -n -t devtmpfs devtmpfs /dev
mount -n -t tmpfs    tmpfs    /run

## device
#mknod /dev/console c 5 1

##
sleep 1

##
ldconfig

##
test -f /etc/banner && cat /etc/banner

## Change to sh
# exec /bin/sh
exec /linuxrc

