
TOPDIR ?= $(CURDIR)


include $(TOPDIR)/rule.mk
# =========================================================================== #

##
$(eval $(call build, library, share, hexdump))

$(eval $(call build, object, executable, test_hexdump))

# =========================================================================== #
include $(TOPDIR)/toplevel.mk
