
TOPDIR ?= $(CURDIR)


include $(TOPDIR)/rule.mk
# =========================================================================== #

##
$(eval $(call build, library, share, hexdump))

# =========================================================================== #
include $(TOPDIR)/toplevel.mk
