TOPDIR:=${CURDIR}


include $(TOPDIR)/include/debug.mk
include $(TOPDIR)/include/devel.mk
msg=$(call devel_warning, "demo")

$(info $(msg))


world:
	$(call devel_warning, "test")
	$(info demdoe)

.PHONY: world
